"""Add audit fields to project members table

Revision ID: 2dd8a9f3c5b1
Revises: c1378ffdc76e
Create Date: 2026-04-17 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd8a9f3c5b1'
down_revision: Union[str, Sequence[str], None] = 'c1378ffdc76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('project_members', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_members', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_members', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('project_members', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('project_members', sa.Column('deleted_by', sa.UUID(), nullable=True))
    
    # Add foreign key constraints for audit user references
    op.create_foreign_key(
        'fk_project_members_created_by_users',
        'project_members',
        'users',
        ['created_by'],
        ['id']
    )
    op.create_foreign_key(
        'fk_project_members_updated_by_users',
        'project_members',
        'users',
        ['updated_by'],
        ['id']
    )
    op.create_foreign_key(
        'fk_project_members_deleted_by_users',
        'project_members',
        'users',
        ['deleted_by'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_project_members_deleted_by_users', 'project_members', type_='foreignkey')
    op.drop_constraint('fk_project_members_updated_by_users', 'project_members', type_='foreignkey')
    op.drop_constraint('fk_project_members_created_by_users', 'project_members', type_='foreignkey')
    op.drop_column('project_members', 'deleted_by')
    op.drop_column('project_members', 'updated_by')
    op.drop_column('project_members', 'created_by')
    op.drop_column('project_members', 'deleted_at')
    op.drop_column('project_members', 'updated_at')
    op.drop_column('project_members', 'created_at')
    # ### end Alembic commands ###
