"""add_allowed_projects_column_to_subscriptions

Revision ID: 661a98166ed1
Revises: e537108716dc
Create Date: 2026-04-18 18:05:35.741208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661a98166ed1'
down_revision: Union[str, Sequence[str], None] = 'e537108716dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('allowed_projects', sa.Float(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'allowed_projects')
    # ### end Alembic commands ###
