"""create comment, replies and worklog table

Revision ID: a502de9e5f1c
Revises: f004b8983c4c
Create Date: 2026-04-10 16:27:48.916079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a502de9e5f1c'
down_revision: Union[str, Sequence[str], None] = 'f004b8983c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tickets_project_and_id', 'tickets', ['project_id', 'id'])
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'created_by'], ['project_members.project_id', 'project_members.id'], name='fk_comments_created_by_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'deleted_by'], ['project_members.project_id', 'project_members.id'], name='fk_comments_deleted_by_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'ticket_id'], ['tickets.project_id', 'tickets.id'], name='fk_comments_ticket_project_match'),
    sa.ForeignKeyConstraint(['project_id', 'updated_by'], ['project_members.project_id', 'project_members.id'], name='fk_comments_updated_by_project_member'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['project_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_comments_project_and_id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('work_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'created_by'], ['project_members.project_id', 'project_members.id'], name='fk_work_logs_created_by_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'deleted_by'], ['project_members.project_id', 'project_members.id'], name='fk_work_logs_deleted_by_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'ticket_id'], ['tickets.project_id', 'tickets.id'], name='fk_work_logs_ticket_project_match'),
    sa.ForeignKeyConstraint(['project_id', 'updated_by'], ['project_members.project_id', 'project_members.id'], name='fk_work_logs_updated_by_project_member'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['project_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_logs_id'), 'work_logs', ['id'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('reply', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'comment_id'], ['comments.project_id', 'comments.id'], name='fk_replies_comment_project_match'),
    sa.ForeignKeyConstraint(['project_id', 'created_by'], ['project_members.project_id', 'project_members.id'], name='fk_replies_created_by_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'deleted_by'], ['project_members.project_id', 'project_members.id'], name='fk_replies_deleted_by_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'updated_by'], ['project_members.project_id', 'project_members.id'], name='fk_replies_updated_by_project_member'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['project_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_replies_project_and_id')
    )
    op.create_index(op.f('ix_replies_id'), 'replies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tickets_project_and_id', 'tickets', type_='unique')
    op.drop_index(op.f('ix_replies_id'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_work_logs_id'), table_name='work_logs')
    op.drop_table('work_logs')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
