"""extract audit fields into reusable mixin and remove duplication across models

Revision ID: ba2d05eac41d
Revises: a502de9e5f1c
Create Date: 2026-04-10 17:40:53.737268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2d05eac41d'
down_revision: Union[str, Sequence[str], None] = 'a502de9e5f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
