"""extract audit fields into reusable mixin and remove duplication across models

Revision ID: df34b4aade45
Revises: ba2d05eac41d
Create Date: 2026-04-10 18:17:33.727345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df34b4aade45'
down_revision: Union[str, Sequence[str], None] = 'ba2d05eac41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
