"""create project_members,tickets table

Revision ID: f004b8983c4c
Revises: bb1f9056b86f
Create Date: 2026-04-10 15:28:23.273190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f004b8983c4c'
down_revision: Union[str, Sequence[str], None] = 'bb1f9056b86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        DECLARE fk record;
        BEGIN
            FOR fk IN
                SELECT c.conname
                FROM pg_constraint c
                JOIN pg_class t ON t.oid = c.conrelid
                WHERE c.contype = 'f'
                  AND t.relname = 'users'
                  AND pg_get_constraintdef(c.oid) LIKE 'FOREIGN KEY (role_id)%REFERENCES roles(id)%'
            LOOP
                EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', fk.conname);
            END LOOP;
        END
        $$;
        """
    )
    op.execute("ALTER TABLE roles ALTER COLUMN id DROP DEFAULT")
    op.alter_column(
        "roles",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using=(
            "(substring(lpad(to_hex(id), 32, '0') from 1 for 8) || '-' || "
            "substring(lpad(to_hex(id), 32, '0') from 9 for 4) || '-' || "
            "substring(lpad(to_hex(id), 32, '0') from 13 for 4) || '-' || "
            "substring(lpad(to_hex(id), 32, '0') from 17 for 4) || '-' || "
            "substring(lpad(to_hex(id), 32, '0') from 21 for 12))::uuid"
        ),
    )
    op.alter_column(
        "users",
        "role_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using=(
            "(substring(lpad(to_hex(role_id), 32, '0') from 1 for 8) || '-' || "
            "substring(lpad(to_hex(role_id), 32, '0') from 9 for 4) || '-' || "
            "substring(lpad(to_hex(role_id), 32, '0') from 13 for 4) || '-' || "
            "substring(lpad(to_hex(role_id), 32, '0') from 17 for 4) || '-' || "
            "substring(lpad(to_hex(role_id), 32, '0') from 21 for 12))::uuid"
        ),
    )
    op.create_foreign_key(
        "fk_users_role_id_roles",
        "users",
        "roles",
        ["role_id"],
        ["id"],
    )
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('project_manager_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_project_member_project_and_id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_user_project')
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('ticket_type', sa.String(length=50), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'assignee_id'], ['project_members.project_id', 'project_members.id'], name='fk_tickets_assignee_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'created_by'], ['project_members.project_id', 'project_members.id'], name='fk_tickets_created_by_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'deleted_by'], ['project_members.project_id', 'project_members.id'], name='fk_tickets_deleted_by_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'resolved_by'], ['project_members.project_id', 'project_members.id'], name='fk_tickets_resolved_by_project_member'),
    sa.ForeignKeyConstraint(['project_id', 'updated_by'], ['project_members.project_id', 'project_members.id'], name='fk_tickets_updated_by_project_member'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['project_members.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['project_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_constraint('fk_users_role_id_roles', 'users', type_='foreignkey')
    op.alter_column(
        "users",
        "role_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="(('x' || right(replace(role_id::text, '-', ''), 8))::bit(32)::int)",
    )
    op.alter_column(
        "roles",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="(('x' || right(replace(id::text, '-', ''), 8))::bit(32)::int)",
    )
    op.execute("CREATE SEQUENCE IF NOT EXISTS roles_id_seq OWNED BY roles.id")
    op.execute("SELECT setval('roles_id_seq', COALESCE((SELECT MAX(id) FROM roles), 1), true)")
    op.execute("ALTER TABLE roles ALTER COLUMN id SET DEFAULT nextval('roles_id_seq')")
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
