"""Add is_active column to all models for soft delete

Revision ID: 11176e08131c
Revises: 21157c8c6997
Create Date: 2026-04-15 23:14:47.167880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11176e08131c'
down_revision: Union[str, Sequence[str], None] = '21157c8c6997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('replies', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('roles', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('roles', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'roles', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'])
    op.add_column('subscriptions', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('subscriptions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('subscriptions', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('subscriptions', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'users', ['deleted_by'], ['id'])
    op.add_column('tickets', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('work_logs', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_logs', 'is_active')
    op.drop_column('tickets', 'is_active')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'deleted_by')
    op.drop_column('subscriptions', 'updated_by')
    op.drop_column('subscriptions', 'created_by')
    op.drop_column('subscriptions', 'deleted_at')
    op.drop_column('subscriptions', 'updated_at')
    op.drop_column('subscriptions', 'created_at')
    op.drop_column('subscriptions', 'is_active')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'deleted_by')
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_by')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'is_active')
    op.drop_column('replies', 'is_active')
    op.drop_column('organizations', 'is_active')
    op.drop_column('comments', 'is_active')
    # ### end Alembic commands ###
